@startuml
actor User
participant ":NextStep" as NextStep
participant ":Parser" as Parser
participant ":DeleteCommand" as DeleteCommand
participant ":InternshipList" as InternshipList
participant ":Storage" as Storage
participant "<<Class>>\nUi" as Ui
skinparam sequenceReferenceBackgroundColor white

User -> NextStep : enters "delete 1"
activate NextStep

NextStep -> Parser : processCommand(input)
activate Parser

create DeleteCommand
Parser -> DeleteCommand : createCommand()
activate DeleteCommand
DeleteCommand --> Parser : return command
deactivate DeleteCommand

Parser -> DeleteCommand : execute()
activate DeleteCommand

ref over DeleteCommand
  parseIndex(input) & index validation
end ref

DeleteCommand -> InternshipList : deleteInternship(index)


DeleteCommand -> Storage : save(internships)

DeleteCommand -> Ui : printDeleteSuccess(removed)
activate Ui
Ui -> User : show deletion success message
Ui --> DeleteCommand
deactivate Ui

DeleteCommand --> Parser
deactivate DeleteCommand

Parser --> NextStep
deactivate Parser

NextStep --> User
deactivate NextStep
@enduml
