@startuml
'https://plantuml.com/sequence-diagram

actor User
participant ":NextStep" as NextStep
participant ":Parser" as Parser
participant ":DeleteCommand" as DeleteCommand
participant ":InternshipList" as InternshipList
participant ":Internship" as Internship
participant ":Storage" as Storage
participant "<<Class>> \nUi" as Ui

User -> NextStep : enters "delete 1"
activate NextStep

NextStep -> Parser : processCommand(input)
activate Parser

Parser -> DeleteCommand : createCommand()
activate DeleteCommand
DeleteCommand --> Parser : return command
deactivate DeleteCommand

Parser -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> DeleteCommand : parseIndex(input)
activate DeleteCommand #lightblue
DeleteCommand --> DeleteCommand : return index
deactivate DeleteCommand

DeleteCommand -> InternshipList : deleteInternship(index)
activate InternshipList
InternshipList -> Internship : removeAt(index)
activate Internship
Internship --> InternshipList : return removedInternship
deactivate Internship
InternshipList --> DeleteCommand : return removedInternship
deactivate InternshipList

DeleteCommand -> Storage : save(internships)
activate Storage
Storage --> DeleteCommand
deactivate Storage

DeleteCommand -> Ui : printDeleteSuccess(removedInternship)
activate Ui
Ui --> DeleteCommand
deactivate Ui

DeleteCommand --> Parser
deactivate DeleteCommand

Parser --> NextStep
deactivate Parser

NextStep --> User : shows success message
deactivate NextStep
@enduml
